services:

  watchtower:
    image: ghcr.io/containrrr/watchtower:1.7.1
    restart: always
    command:
      - "--label-enable"
      - "--interval"
      - "300"
      - "--cleanup"
      - "--rolling-restart"
    environment:
      DOCKER_API_VERSION: "1.52"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.6
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # ENTRYPOINTS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # HTTPS + LETSENCRYPT
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=dorjoo@hire-test.cloud"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      # (prod-д dashboard унтраасан)
      # - "--api.insecure=true"

    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"   # ❌ prod-д нээхгүй

    volumes:
      - letsencrypt:/letsencrypt
      - /run/docker.sock:/run/docker.sock:ro

  # ------------------------
  # DATABASE
  # ------------------------
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: hire
      POSTGRES_USER: dorjoo
      POSTGRES_PASSWORD: dorjooX0
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  # ------------------------
  # CORE BACKEND
  # ------------------------
  core:
    image: ghcr.io/dorjoohover/hire_backend_core:test
    restart: always
    env_file:
      - ${ENV_FILE}
    volumes:
      - /var/lib/hire/uploads:/app/uploads:rw
      - /var/log/hire/core:/app/logs:rw
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core.rule=Host(`api.hire-test.cloud`)"
      - "traefik.http.routers.core.entrypoints=websecure"
      - "traefik.http.routers.core.tls.certresolver=myresolver"
      - "traefik.http.services.core.loadbalancer.server.port=5000"
      - "com.centurylinklabs.watchtower.enable=true"


  # ------------------------
  # REPORT BACKEND
  # ------------------------
  report:
    image: ghcr.io/dorjoohover/hire_report:test
    restart: always
    env_file:
      - ${ENV_FILE}
    volumes:
      - /var/lib/hire/uploads:/app/uploads:rw
      - /var/log/hire/report:/app/logs:rw
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.report.rule=Host(`report.hire-test.cloud`)"
      - "traefik.http.routers.report.entrypoints=websecure"
      - "traefik.http.routers.report.tls.certresolver=myresolver"
      - "traefik.http.services.report.loadbalancer.server.port=4000"
      - "com.centurylinklabs.watchtower.enable=true"
  web:
    image: ghcr.io/usukhbaya12/hire-web:dev
    restart: always
    env_file:
      - ${ENV_FILE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`hire-test.cloud`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
  admin:
    image: ghcr.io/usukhbaya12/hire-admin:dev
    restart: always
    env_file:
      - ${ENV_FILE}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.hire-test.cloud`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=myresolver"
      - "traefik.http.services.admin.loadbalancer.server.port=3001"
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  pgdata:
  redisdata:
  letsencrypt: